"""empty message

Revision ID: acf4d3e2f28f
Revises: 49d82b82bf24
Create Date: 2023-11-17 22:22:11.513441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf4d3e2f28f'
down_revision = '49d82b82bf24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index('ix_features_fname')
        batch_op.drop_index('ix_features_kname')

    op.drop_table('features')
    with op.batch_alter_table('predsets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feat_set', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predsets', schema=None) as batch_op:
        batch_op.drop_column('feat_set')

    op.create_table('features',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('kname', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index('ix_features_kname', ['kname'], unique=False)
        batch_op.create_index('ix_features_fname', ['fname'], unique=False)

    # ### end Alembic commands ###
